title: Dumebi's Blog
author: Dumebi Iwuchukwu
email: me@dum3bi.com
description: > # this means to ignore newlines until "baseurl:"
  The personal blog Of Dumebi Iwuchukwu, Where he writes about tech, design and strategy.

# social links
twitter_username: @dum3bi
github_username: @dum3bi

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minimal
